repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: repository-validation
        name: repository validation
        entry: python3 scripts/validate_repository.py
        language: system
        pass_filenames: false

      - id: structured-file-validation
        name: Validate JSON Schema and YAML
        entry: python3 scripts/validate_structured_files.py
        language: system
        pass_filenames: false
